### PR TITLE
do not commit compiled lib/

### PR DESCRIPTION
**Pull request by deepsweet**

### CODE REVIEW

**Comment by douglasduteil** [comment]
Ohh sweet hook :+1: 
Can you rebase it ?

**Comment by deepsweet** [comment]
done.

**Comment by douglasduteil** [comment]
And again sorry...

**Comment by deepsweet** [comment]
go :smile:

**Comment by douglasduteil** [comment]
Coooool. Thanks a lot @deepsweet 

New release soon :tada:

**Pull request merged**
