### PR TITLE
fix to babel/babel#908

### PR DESCRIPTION
**Pull request by simonzack**

### CODE REVIEW

**Comment by mairatma** [comment]
:+1:

I was just about to send a pull request just like this, this fix is important since isparta is now breaking when installed because of babel's update.

**Comment by nicksrandall** [comment]
Thanks @simonzack! I hope this gets merged soon!

**Comment by jmeas** [comment]
ping @douglasduteil. This is breaking a lot of things downstream.

**Comment by douglasduteil** [comment]
Alright fixed in 6b54430796464d1653017b760c2845192006725d
Thanks @simonzack

**Comment by jmeas** [comment]
Thanks @douglasduteil !

**Pull request closed without merging**
