### PR TITLE
Add basic support for istanbul ignore

### LINKED ISSUE #24: How to skip statements/functions?
This function is only called when there is an error (it displays an error dialog on web page). It is not useful to test the coverage of this function.
 
screen shot 2015-03-05 at 17 11 26

In Istanbul, you could use `/* istanbul skip next */`, but it doesn't work in Isparta. I also tried `/* isparta ignore next */` without success.

### PR DESCRIPTION
**Pull request by taion**
Fixes #24 

I kept the behavior from `_fnMapTransformer` of completely skipping the `skip` key.

### CODE REVIEW

**Comment by taion** [comment]
Added a little bit more to fix some bugs with the current logic on `_fnMapTransformer`.

**Comment by taion** [comment]
Think I finally have the function stuff correct.

**Comment by taion** [comment]
Has anybody had a chance to look at this? We're starting to use isparta for a few of our projects, and would like to be able to use the istanbul ignore pragmas in our code.

**Comment by douglasduteil** [comment]
Wow that a great clean up @taion 
Thanks

**Pull request merged**
