### PR TITLE
Use Object.assign() ponyfill

### LINKED ISSUE #63: Error: Object.assign is not a function
```
Z:\project\node_modules\isparta\lib\cli.js:197
    _istanbul.hook.hookRequire(matchFn, transformer, Object.assign({ verbose:
                                                            ^
TypeError: undefined is not a function
```

### PR DESCRIPTION
**Pull request by jedmao**
Fixes #63

### CODE REVIEW

**Comment by deepsweet** [comment]
:+1:

**Comment by nkbt** [comment]
:+1:

**Comment by douglasduteil** [comment]
Thanks

**Comment by nkbt** [comment]
@douglasduteil great, thanks!

**Pull request merged**
